OAI:
  set: driver
  timestampUTC: '2019-01-16T20:44:42Z'
  url: https://www.alexandria.unisg.ch/cgi/oai2
  metadataPrefix: oai_dc
Processing:
  Default:
    stoppageTime: '2019-01-20T12:55:24Z'
Producer:
  client_id: oai-alexrepo-producer
Topics: ALEXREPO
