OAI:
  metadataPrefix: oai_dc
  timestampUTC: '2019-01-23'
  url: http://www.e-codices.unifr.ch/oai/oai.php
Processing:
  Default:
    granularity: YYYY-MM-DD
    stoppageTime: '2019-01-23T11:34:22Z'
Producer:
  client_id: oai-ecod-producer
Topics: ECOD
