OAI:
  timestampUTC: '2019-01-16T20:44:42Z'
  url: http://research-collection.ethz.ch/oai/doi
  metadataPrefix: qdc
Processing:
  Default:
    stoppageTime: '2019-01-20T12:55:24Z'
Producer:
  client_id: oai-ethresearch-producer
Topics: ETHRESEARCH
