AdminClient:
  client_id: oai-admin-hemu-producer
OAI:
  set: marcxml
  timestampUTC: '2019-02-14T01:01:01Z'
  url: http://aleph.ag.ch/OAI
  metadataPrefix: marcxml
Processing:
  Default:
    stoppageTime: '2019-01-20T12:55:24Z'
Producer:
  client_id: oai-hemu-producer
Topic:
  name: HEMU
