AdminClient:
  client_id: oai-admin-idsbb-producer
OAI:
  set: SWISSBIB-FULL-OAI
  timestampUTC: '2019-01-16T20:44:42Z'
  url: http://aleph.unibas.ch/OAI
Processing:
  Default:
    stoppageTime: '2019-01-20T12:55:24Z'
Producer:
  client_id: oai-idsbb-producer
Topic:
  name: IDSBB
