OAI:
  set: SWISSBIB-FULL-OAI
  setSpec: SWISSBIB-FULL-OAI
  stoppageTime: '2019-01-16T21:44:45Z'
  timestampUTC: '2019-01-16T20:44:42Z'
  url: http://aleph.unibas.ch/OAI
Processing:
  Default:
    stoppageTime: '2019-01-20T12:55:24Z'
Producer:
  client_id: oai-idsbb-producer
Topics: IDSBB
