AdminClient:
  client_id: oai-admin-idssg-producer
OAI:
  set: SWISSBIB-FULL-HSB01
  timestampUTC: '2019-01-28T01:01:01Z'
  url: http://aleph.unisg.ch/cgi-bin/OAI
Processing:
  Default:
    stoppageTime: '2019-01-27T20:44:38Z'
Producer:
  client_id: oai-idssg-producer
Topic:
  name: IDSSG
