OAI:
  set: SWISSBIB-FULL-HSB01
  timestampUTC: '2019-01-16T20:44:42Z'
  url: http://aleph.unisg.ch/cgi-bin/OAI
Processing:
  Default:
    stoppageTime: '2019-01-16T12:55:24Z'
Producer:
  client_id: oai-idssg-producer
Topics: IDSSG
