OAI:
  metadataPrefix: marc21
  httpproxy: None
  resumptionToken: None
  until: None
Processing:
  Default:
    granularity: YYYY-MM-DDThh:mm:ssZ
    baseDir: /swissbib/harvesting
    deleteDirIncoming: '{baseDir}/deleteOAI'
    encodeUnicodeAsUTF8: null
    processorType: OAI
    recordBodyRegEx: .*?(<marc:record.*?</marc:record>).*?</metadata></record>
    identifierkey: .*?<identifier>(.*?)</identifier>.*
    eMailNotifification: [
      'guenter.hipler@unibas.ch',
      'bobobabo@bluewin.ch',
      'silvia.witzig@unibas.ch',
      'matthias.edel@unibas.ch',
      'lionel.walther@unibas.ch']
  OAI: null
  WebDav:
    incomingDir: '{baseDir}/rero.webdav'
Producer:
  bootstrap_servers: sb-uka1.swissbib.unibas.ch:9092,sb-uka2.swissbib.unibas.ch:9093,sb-uwf3.swissbib.unibas.ch:9094
Topics: oai_sampler_basic_topic