AdminClient:
  client_id: oai-admin-sbt-producer
OAI:
  set: SWISSBIB-FULL-OAI
  timestampUTC: '2019-01-28T01:01:01Z'
  url: http://aleph.unibas.ch/OAI
Processing:
  Default:
    stoppageTime: '2019-01-20T12:55:24Z'
Producer:
  client_id: oai-sbt-producer
Topic:
  name: IDSSBT
