OAI:
  set: SwisOAI
  timestampUTC: '2019-01-16T20:44:42Z'
  url: https://eu01.alma.exlibrisgroup.com/view/oai/41BCULAUSA_LIB/request
Processing:
  Default:
    stoppageTime: '2019-01-20T12:55:24Z'
Producer:
  client_id: oai-vaud-lib-producer
Topics: VAUD
