language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
script:
  - pytest
after_success:
  - git config --global user.name "semantic-release (via TravisCI)"
  - git config --global user.email "semantic-release@travis"
  - pip install python-semantic-release
  - semantic-release publish