AdminClient:
  client_id: webdav-admin-ecod-producer
Processing:
  Default:
    recordBodyRegEx: <record><header.*?>.*?</metadata></record>
    stoppageTime: '2019-02-12T22:45:06Z'
Producer:
  client_id: webdav-rero-producer
Topic:
  name: RERO
WebDav:
  basedirwebdav: '{basedir}/rero.webdav'
  latestProcDate: '2019_01_16'
  processMode: ONLY_NEW_DELIVERD
  singleRecordIterator: <record><header.*?>.*?</metadata></record>
  srcDir: '{basedir}/rero-src'
  workingDir: '{basedir}/rero-working'
