Kafka:
  host: localhost:9092
  partition: 0
  topicToUse: HSG1
OAI:
  granularity: YYYY-MM-DDThh:mm:ssZ
  httpproxy: null
  metadataPrefix: marc21
  resumptionToken: null
  setName: null
  setSpec: SWISSBIB-FULL-HSB01
  stoppageTime: '2018-07-05T20:51:36Z'
  timestampUTC: '2018-07-05T18:51:32Z'
  until: 2018-03-30T18:47:9Z
  url: http://aleph.unisg.ch/cgi-bin/OAI
Processing:
  encodeUnicodeAsUTF8: null
  processorType: OAI
  recordBodyRegEx: .*?(<marc:record.*?</marc:record>).*?</metadata></record>
